### ISSUE TITLE
deployer busted as usual, need to document restart steps

### ISSUE THREAD

**Issue by karlht** [mozilla/browserid_deployer#1]
Several people noticed that the dev.login.anosrep.org server went down around 330 today, see [ircloggr](http://irclog.gr/#show/irc.mozilla.org/identity/289974) for deets.

This bug tracks work to get deployer and dev restarted + document the process so we put this particular tragedy of the commons to bed.

**Comment by jaredhirsch** [comment]
http://comments.gmane.org/gmane.comp.mozilla.identity.devel/4202

"our dev deployer ... has a couple bugs that require weekly restarts"

I'm working on documenting a procedure for troubleshooting, I'll open a PR when ready. hopefully @lloyd or @rfk can have a look.

**Comment by jaredhirsch** [comment]
here's the recurring snippet from the deployer logs (onboard the deployer awsbox at /home/app/var/log/deploy_server.js.log):

[app@ip-10-191-18-206 ~]$ tail -f var/log/deploy_server.js.log 
progress: 200
progress: https://github.com/downloads/lloyd/node-statsd/0509f85.tgz
progress: npm
progress: WARN
progress: prefer global
progress: node-inspector@0.2.0beta3 should be installed with -g
progress: > browserid@1.0.0-b2 postinstall /home/app/browserid_repo
progress: > node ./scripts/postinstall.js
progress: reading .awsbox.json
progress: attempting to set up VM "login.dev.anosrep.org (efc1abc)"
progress: events.js:68
progress: throw arguments[1]; // Unhandled 'error' event
progress: ^
progress: Error: connect ETIMEDOUT
progress: at errnoException (net.js:769:11)
progress: at Object.afterConnect [as oncomplete](net.js:760:19)
error: true
progress: fatal error: Error: Command failed:
progress: events.js:68
progress: throw arguments[1]; // Unhandled 'error' event
progress: ^
progress: Error: connect ETIMEDOUT
progress: at errnoException (net.js:769:11)
progress: at Object.afterConnect [as oncomplete](net.js:760:19)

**Comment by jaredhirsch** [comment]
@jrgm got to the bottom of today's bug, the Zerigo API is down:

``` bash
jrgm        tcp        0      1 10.191.18.206:45422         64.27.57.8:80               SYN_SENT    3823/awsbox         5:53
jrgm        dig -x 64.27.57.8           5:53
jrgm        8.57.27.64.in-addr.arpa. 900    IN      PTR     dns.zerigo.com.         5:54
jrgm        So, deployer is timing out when it tries to talk to the zerigo API.         5:54
jrgm        and ETIMEDOUT
```

Closing this bug as unfixable for the moment. Opening a new bug to document troubleshooting steps in the readme.
